export enum AppPermission {
	// Proyectos
	PROJECT_CREATE = 'PROJECT_CREATE',
	PROJECT_READ = 'PROJECT_READ',
	PROJECT_UPDATE = 'PROJECT_UPDATE',
	PROJECT_DELETE = 'PROJECT_DELETE',

	// Trabajadores
	WORKER_CREATE = 'WORKER_CREATE',
	WORKER_READ = 'WORKER_READ',
	WORKER_UPDATE = 'WORKER_UPDATE',
	WORKER_DELETE = 'WORKER_DELETE',

	// Recursos (Materiales, Mano de Obra, Equipos)
	RESOURCE_CREATE = 'RESOURCE_CREATE',
	RESOURCE_READ = 'RESOURCE_READ',
	RESOURCE_UPDATE = 'RESOURCE_UPDATE',
	RESOURCE_DELETE = 'RESOURCE_DELETE',

	// Usuarios
	USER_CREATE = 'USER_CREATE',
	USER_READ = 'USER_READ',
	USER_UPDATE = 'USER_UPDATE',
	USER_DELETE = 'USER_DELETE',

	// Inventario
	INVENTORY_CREATE = 'INVENTORY_CREATE',
	INVENTORY_READ = 'INVENTORY_READ',
	INVENTORY_UPDATE = 'INVENTORY_UPDATE',
	INVENTORY_DELETE = 'INVENTORY_DELETE',

	// Otros
	SECURITY_READ = 'SECURITY_READ',
	AUDIT_READ = 'AUDIT_READ',
}
